automatic folder creation, other bugs

diff --git a/getmail_gmail b/getmail_gmail
--- a/getmail_gmail
+++ b/getmail_gmail
@@ -12,6 +12,97 @@
 
 exit 1
 
+
+#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
+#-#-#-# <OPTIONS> #-#-#-#-#-#-#
+
+
+debug=1                                 #uncomment this line to enable debugging output
+                                        #NOTES:
+                                        #       Along with other information, this logs the sha1 of the incoming message plaintext to the logfile.
+                                        #       Comment this out for use in production.
+
+
+#tarcmd="/usr/local/src/tar-1.26/output/bin/tar"        #tar must support the --transform switch, uncomment this line if you had to compile tar manually
+
+
+#-#-#-# <END OPTIONS> #-#-#-#-#
+#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
+
+
+debug="${debug-0}"
+
+if [[ "${debug}" != "1" ]] ; then
+        exec > >(cat /dev/null) 2>&1            #keep script quiet unless debug=1
+fi
+
+if [[ "${debug}" != "1" ]] && [[ "${debug}" != "0" ]] ; then
+        fail "debug must be set to 0 or 1, currently debug=${debug}"    #note this will never actually print anything, because debug != 1, but we want to fail here anyway
+fi
+
+show_help()
+{ cat <<EOF
+
+	TODO
+
+EOF
+}
+
+
+version() { cat <<EOF
+0.5 ALPHA [Aug 20 2013]
+EOF
+}
+
+
+debug_dump_vars="${debug_dump_vars-0}"
+
+usually_dev_null="${usually_dev_null-/dev/null}"
+
+error_exit_code="${error_exit_code-75}"
+
+
+my_pid=$$
+
+dbg()
+{
+        if [[ "${debug}" == "1" ]] ; then
+                return 0                #return true if debug=1
+        else
+                return 1                #debugging is disabled, stop here
+        fi
+}
+
+log()                                   # print log message if debug=1
+{
+        if dbg ; then
+                test -t 1 && logger -s "[stderr][$PPID][${my_pid}] $*" || logger "[$PPID][${my_pid}] $*"
+        fi
+        return $?
+}
+
+fail()                                  # log error and exit
+{
+        log "fail() ERROR: $*"
+        log "fail() EXITING ${error_exit_code}"
+        exit "${error_exit_code}"
+}
+
+on_ERR()
+{
+        prev_line=`caller`
+        log "on_ERR called from line: ${prev_line}"
+        fail "trapped ERR - on_ERR() called in $0 with $*. Exiting"
+}
+
+trap on_ERR ERR                         # from the man docs on set -o errexit
+
+
+
+
+
+
+
 SOURCE="${BASH_SOURCE[0]}"
 while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
 DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"        # http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
@@ -25,7 +116,7 @@ max_messages_per_session=400000
 
 scriptname=`basename "$0"`
 argcount=1
-usage="user@gmail.com" 
+usage="user@gmail.com"
 test "$#" -ne "${argcount}" && { echo "$0 ${usage}" && exit 1 ; } #"-ge=>=" "-gt=>" "-le=<=" "-lt=<" "-ne=!="
 
 email_address="${1-none}"
@@ -33,9 +124,9 @@ username=$(echo "${email_address}" | cut -d '@' -f 1)
 
 echo "$username"
 
-getmail_archive_folder="${email_archive_folder}/_getmail_${email_address}_archive"
-maildir="${getmail_archive_folder}/_Maildirs"
-maildir_logs="/${getmail_archive_folder}/_getmail_logs"
+getmail_archive_folder="${email_archive_folder}/_getmail_${email_address}"
+maildir="${getmail_archive_folder}/"
+maildir_logs="${getmail_archive_folder}/_getmail_logs"
 notmuch_folder="${getmail_archive_folder}/_notmuch"
 
 test -d "${getmail_archive_folder}" || { echo "${getmail_archive_folder} not found or is not a directory, exiting" && exit 1 ;}
diff --git a/gpgmda_decrypt_msg_once b/gpgmda_decrypt_msg_once
--- a/gpgmda_decrypt_msg_once
+++ b/gpgmda_decrypt_msg_once
@@ -1,69 +1,158 @@
 #!/bin/bash
 
 # gpgmda_decrypt_msg_once is called by gpgmda_to_maildir
+#todo make this stateless... no folder defs, pass the source and des to this script explicit
 
 SOURCE="${BASH_SOURCE[0]}"
 while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
 DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"        # http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
 
+
 source "${DIR}"/bash_import_set_defaults                # set -o nounset; set -o errtrace; set -o errexit; set -o pipefail
 
-email_archive_folder="/home/user/__email_folders"
+
+#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
+#-#-#-# <OPTIONS> #-#-#-#-#-#-#
+
+
+debug=1                                 #uncomment this line to enable debugging output
+                                        #NOTES:
+                                        #       Along with other information, this logs the sha1 of the incoming message plaintext to the logfile.
+                                        #       Comment this out for use in production.
+
+
+#tarcmd="/usr/local/src/tar-1.26/output/bin/tar"        #tar must support the --transform switch, uncomment this line if you had to compile tar manually
+
+
+#-#-#-# <END OPTIONS> #-#-#-#-#
+#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
+
+
+debug="${debug-0}"
+
+if [[ "${debug}" != "1" ]] ; then
+        exec > >(cat /dev/null) 2>&1            #keep script quiet unless debug=1
+fi
+
+if [[ "${debug}" != "1" ]] && [[ "${debug}" != "0" ]] ; then
+        fail "debug must be set to 0 or 1, currently debug=${debug}"    #note this will never actually print anything, because debug != 1, but we want to fail here anyway
+fi
+
+show_help()
+{ cat <<EOF
+
+	TODO
+
+EOF
+}
+
+
+version() { cat <<EOF
+0.5 ALPHA [Aug 20 2013]
+EOF
+}
+
+
+debug_dump_vars="${debug_dump_vars-0}"
+
+usually_dev_null="${usually_dev_null-/dev/null}"
+
+error_exit_code="${error_exit_code-75}"
+
 
 my_pid=$$
 
-argcount=2
-usage="email@domain.com gpg_encrypted_file"
+dbg()
+{
+        if [[ "${debug}" == "1" ]] ; then
+                return 0                #return true if debug=1
+        else
+                return 1                #debugging is disabled, stop here
+        fi
+}
 
-test "$#" -eq "${argcount}" || { echo "ERROR:" && echo "$0 ${usage}" && echo "gpgmda_decrypt_msg_once was passed ${#} args:" && echo "$@" && exit 1 ; } #"-ge=>=" "-gt=>" "-le=<=" "-lt=<" "-ne=!="
+log()                                   # print log message if debug=1
+{
+        if dbg ; then
+                test -t 1 && logger -s "[stderr][$PPID][${my_pid}] $*" || logger "[$PPID][${my_pid}] $*"
+        fi
+        return $?
+}
 
-echo -e "\ngpgmda_decrypt_msg_once was passed ${#} args:" && echo "$@"
+fail()                                  # log error and exit
+{
+        log "fail() ERROR: $*"
+        log "fail() EXITING ${error_exit_code}"
+        exit "${error_exit_code}"
+}
+
+on_ERR()
+{
+        prev_line=`caller`
+        log "on_ERR called from line: ${prev_line}"
+        fail "trapped ERR - on_ERR() called in $0 with $*. Exiting"
+}
+
+trap on_ERR ERR                         # from the man docs on set -o errexit
+
+
+
+argcount=3
+usage="email@domain.com gpg_encrypted_file maildir_output_folder"
+
+test "$#" -eq "${argcount}" || { log "ERROR:" && log "$0 ${usage}" && log "gpgmda_decrypt_msg_once was passed ${#} args:" && log "$@" && exit 1 ; } #"-ge=>=" "-gt=>" "-le=<=" "-lt=<" "-ne=!="
+
+log "gpgmda_decrypt_msg_once was passed ${#} out of ${argcount} required args:" && log "$@"
+
 
 email_address="${1}"
+shift
+echo "${email_address}" | grep -q @ || { log "Invalid email address: ${email_address}, exiting." && exit 1 ; }
 
 
-gpgMaildir_archive_folder="${email_archive_folder}/_gpgMaildirs/${email_address}_archive"
-
-echo "gpgmda_to_maildir using gpgMaildir_archive_folder: ${gpgMaildir_archive_folder}"
-
-gpgmaildir="${gpgMaildir_archive_folder}/_gpgMaildirs/gpgMaildir"
-
-Maildir_archive_folder="${email_archive_folder}/_Maildirs/${email_address}_archive"
-
-maildir="${Maildir_archive_folder}/_Maildirs/Maildir"
-
-
-gpgfile="${2}"
+gpgfile="${1}"
+shift
 echo "gpgfile=${gpgfile}"
-
-gpgfile_name=$(basename "$gpgfile")
-echo "gpgfile_name=${gpgfile_name}"
-
-gpgfile_folder=$(dirname "${gpgfile}")
-echo "gpgfile_folder=${gpgfile_folder}"
-
-gpgfile_subfolder=$(basename "${gpgfile_folder}")
-echo "gpgfile_subfolder=${gpgfile_subfolder}"
-
-#keyid="${3}"
 
 if test ! -s "${gpgfile}"
 then
-	echo "FOUND ZERO LENGTH FILE, CHECK THE MAILSERVER LOGS - ${gpgfile}"
-	timestamp=$(date +%s.%N)
-#	mv "${gpgfile}" /tmp/"${gpgfile_name}"."${timestamp}"
-	exit 0
+	echo "FOUND ZERO LENGTH FILE, EXITING. CHECK THE MAILSERVER LOGS - ${gpgfile}"
+	exit 1
 fi
 
+gpgfile_name=$(basename "$gpgfile")
+echo "gpgfile_name=${gpgfile_name}"
+gpgfile_folder_path=$(dirname "${gpgfile}")
+echo "gpgfile_folder_path=${gpgfile_folder_path}"
+gpgfile_subfolder=$(basename "${gpgfile_folder_path}")
+echo "gpgfile_subfolder=${gpgfile_subfolder}"
+
+
+maildir_folder="${1}"
+shift
+if test ! -d "${maildir_folder}"
+then
+        echo "Destination Maildir folder: ${maildir_ffolder} does not exist. Exiting."
+        exit 0
+fi
+
+
+#email_archive_folder="/home/user/__email_folders"
+#gpgMaildir_archive_folder="${email_archive_folder}/_gpgMaildirs/${email_address}"
+#echo "gpgmda_to_maildir using gpgMaildir_archive_folder: ${gpgMaildir_archive_folder}"
+#gpgmaildir="${gpgMaildir_archive_folder}/gpgMaildir"
+#Maildir_archive_folder="${email_archive_folder}/_Maildirs/${email_address}"
+#maildir="${Maildir_archive_folder}/Maildir"
+#keyid="${3}"
+
+
 file_previously_decrypted=0
+test -s "${maildir_folder}/"*".${gpgfile_name}" && file_previously_decrypted=1
 
 #there are better ways to do this...like using find
-
-test -s "${maildir}/new/"*".${gpgfile_name}" && file_previously_decrypted=1
-
-test -s "${maildir}/cur/"*".${gpgfile_name}" && file_previously_decrypted=1
-
-test -s "${maildir}/.sent/"*".${gpgfile_name}" && file_previously_decrypted=1
+#test -s "${maildir}/new/"*".${gpgfile_name}" && file_previously_decrypted=1
+#test -s "${maildir}/cur/"*".${gpgfile_name}" && file_previously_decrypted=1
+#test -s "${maildir}/.sent/"*".${gpgfile_name}" && file_previously_decrypted=1
 
 
 if [ "${file_previously_decrypted}" == "1" ]; then
@@ -73,8 +162,8 @@ if [ "${file_previously_decrypted}" == "1" ]; then
 else
 	ls -al "${gpgfile}" || { echo "Unable to run ls on ${gpgfile}, exiting without decryption." && exit 1 ; }
 #	echo  "maildir=${maildir} gpgfile_subfolder=${gpgfile_subfolder}"
-	gpg2 -o - --decrypt "${gpgfile}" | tar --transform="s/$/.${gpgfile_name}/" -C  "${maildir}/${gpgfile_subfolder}" -xvf -
+#	gpg2 -o - --decrypt "${gpgfile}" | tar --transform="s/$/.${gpgfile_name}/" -C  "${maildir}/${gpgfile_subfolder}" -xvf -
+	gpg2 -o - --decrypt "${gpgfile}" | tar --transform="s/$/.${gpgfile_name}/" -C  "${maildir_folder}/${gpgfile_subfolder}" -xvf -
 
 fi
-
 exit 0
diff --git a/gpgmda_to_maildir b/gpgmda_to_maildir
--- a/gpgmda_to_maildir
+++ b/gpgmda_to_maildir
@@ -1,12 +1,96 @@
 #!/bin/bash
-
 #date >> ~/blah
-
 #set -x
-
-echo "entering gpgmda_to_maildir"
-
 # convert a gpgMaildir folder containing encrypted messages to a normal Maildir folder.
+
+
+
+#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
+#-#-#-# <OPTIONS> #-#-#-#-#-#-#
+
+
+debug=1                                 #uncomment this line to enable debugging output
+                                        #NOTES:
+                                        #       Along with other information, this logs the sha1 of the incoming message plaintext to the logfile.
+                                        #       Comment this out for use in production.
+
+
+#tarcmd="/usr/local/src/tar-1.26/output/bin/tar"        #tar must support the --transform switch, uncomment this line if you had to compile tar manually
+
+
+#-#-#-# <END OPTIONS> #-#-#-#-#
+#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
+
+
+debug="${debug-0}"
+
+if [[ "${debug}" != "1" ]] ; then
+        exec > >(cat /dev/null) 2>&1            #keep script quiet unless debug=1
+fi
+
+if [[ "${debug}" != "1" ]] && [[ "${debug}" != "0" ]] ; then
+        fail "debug must be set to 0 or 1, currently debug=${debug}"    #note this will never actually print anything, because debug != 1, but we want to fail here anyway
+fi
+
+show_help()
+{ cat <<EOF
+
+	TODO
+
+EOF
+}
+
+
+version() { cat <<EOF
+0.5 ALPHA [Aug 20 2013]
+EOF
+}
+
+
+debug_dump_vars="${debug_dump_vars-0}"
+
+usually_dev_null="${usually_dev_null-/dev/null}"
+
+error_exit_code="${error_exit_code-75}"
+
+
+my_pid=$$
+
+dbg()
+{
+        if [[ "${debug}" == "1" ]] ; then
+                return 0                #return true if debug=1
+        else
+                return 1                #debugging is disabled, stop here
+        fi
+}
+
+log()                                   # print log message if debug=1
+{
+        if dbg ; then
+                test -t 1 && logger -s "[stderr][$PPID][${my_pid}] $*" || logger "[$PPID][${my_pid}] $*"
+        fi
+        return $?
+}
+
+fail()                                  # log error and exit
+{
+        log "fail() ERROR: $*"
+        log "fail() EXITING ${error_exit_code}"
+        exit "${error_exit_code}"
+}
+
+on_ERR()
+{
+        prev_line=`caller`
+        log "on_ERR called from line: ${prev_line}"
+        fail "trapped ERR - on_ERR() called in $0 with $*. Exiting"
+}
+
+trap on_ERR ERR                         # from the man docs on set -o errexit
+
+
+
 
 SOURCE="${BASH_SOURCE[0]}"
 while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
@@ -14,7 +98,6 @@ DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"        # http://stackoverflow.c
 
 #source "${DIR}"/bash_import_set_defaults                # set -o nounset; set -o errtrace; set -o errexit; set -o pipefail
 source ~/cfg/bash_libs/shell_command_lock/shell_command_lock
-#source "${DIR}"/bash_import_email_archive_folder        # defines email_archive_folder
 
 email_archive_folder="/home/user/__email_folders"
 
@@ -24,40 +107,39 @@ scriptname=`basename "$0"`
 argcount=1
 usage="email@domain.com"
 
-test "$#" -eq "${argcount}" || { echo "$0 ${usage}" && exit 1 ; } #"-ge=>=" "-gt=>" "-le=<=" "-lt=<" "-ne=!="
+test "$#" -eq "${argcount}" || { log "$0 ${usage}" && exit 1 ; } #"-ge=>=" "-gt=>" "-le=<=" "-lt=<" "-ne=!="
 
 scriptname=`basename "$0"`
 
 email_address="${1}"
 
-#gpgMaildir_archive_folder="${email_archive_folder}/_gpgMaildir_${email_address}_archive"
-gpgMaildir_archive_folder="${email_archive_folder}/_gpgMaildirs/${email_address}_archive"
+gpgMaildir_archive_folder="${email_archive_folder}/_gpgMaildirs/${email_address}"
 
-echo "gpgmda_to_maildir using gpgMaildir_archive_folder: ${gpgMaildir_archive_folder}"
+log "gpgmda_to_maildir using gpgMaildir_archive_folder: ${gpgMaildir_archive_folder}"
 
-gpgmaildir="${gpgMaildir_archive_folder}/_gpgMaildirs/gpgMaildir"
+gpgmaildir="${gpgMaildir_archive_folder}/gpgMaildir"
 
-Maildir_archive_folder="${email_archive_folder}/_Maildirs/${email_address}_archive"
+Maildir_archive_folder="${email_archive_folder}/_Maildirs/${email_address}"
 
-maildir="${Maildir_archive_folder}/_Maildirs/Maildir"
+maildir="${Maildir_archive_folder}/Maildir"
 
 
 fail()
 {
-        echo "fail() ERROR: $*"
-        echo "fail() EXITING"
+        log "fail() ERROR: $*"
+        log "fail() EXITING"
         exit 1
 }
 
 
-echo "Checking for default-recipient in ~/.gnupg/gpg.conf"
+log "Checking for default-recipient in ~/.gnupg/gpg.conf"
 grep "^default-recipient" ~/.gnupg/gpg.conf > /dev/null 2>&1 || { fail "default-recipient is not defined in ~/.gnupg/gpg.conf," ; exit 1 ; }
 
-echo "Checking to see if ${gpgmaildir} exists"
-test -d "${gpgmaildir}" || { echo "gpgMaildir ${gpgmaildir} not found, exiting" && exit 1 ; }
+log "Checking to see if ${gpgmaildir} exists"
+test -d "${gpgmaildir}" || { log "gpgMaildir ${gpgmaildir} not found, exiting" && exit 1 ; }
 
-echo "Checking to see if ${maildir} exists"
-test -d "${maildir}" || { mkdir -p "${maildir}/new" && mkdir -p "${maildir}/tmp" && mkdir -p "${maildir}/cur" && mkdir -p "${maildir}/.sent" || exit 1; }
+log "Checking to see if ${maildir} exists"
+test -d "${maildir}" || { log "${maildir} does not exist! Creating it along with the standard maildir folders." && mkdir -p "${maildir}/new" && mkdir -p "${maildir}/tmp" && mkdir -p "${maildir}/cur" && mkdir -p "${maildir}/.sent" || exit 1; }
 
 
 random_string()
@@ -73,17 +155,143 @@ warm_up_gpg()
 	decrypt_test=0
 
 	while [[ "${decrypt_test}" != "1" ]]; do
-		echo "generating gpg test string"
+		log "generating gpg test string"
 		test_string=$(random_string) || fail "something went wrong generating a random test string"
 		echo "${test_string}" | gpg --yes --trust-model always --throw-keyids --encrypt -o - | gpg --decrypt | grep "${test_string}" && decrypt_test=1
 	done
-	echo "done warming up gpg"
+	log "done warming up gpg"
 }
+
+test_and_decrypt_all_files_in_folder()
+{
+	log "gpgmda_to_maildir test_and_decrypt_all_files_in_folder()"
+	input_folder="${1}"
+	# this goes through every file... much slower than the default method.
+	# parallel is GNU parallel http://www.gnu.org/software/parallel/
+
+	test -d "${input_folder}" || { log "Folder: ${input_folder} does not exist. Create it. Exiting" && exit 1 ; }
+
+	warm_up_gpg
+
+	log -e "\nworking on ${input_folder}"
+	log "email_address: ${email_address}"
+	number_of_files_to_process=`find "${input_folder}" -type f | wc -l`
+	log "about to process ${number_of_files_to_process} files from ${input_folder}"
+	if [[ "${number_of_files_to_process}" -gt "0" ]]
+	then
+		log "attempting to run gnu parallel on ${input_folder}"
+		find "${input_folder}" -type f | parallel --gnu --halt-on-error 1 --keep-order --eta -j+0 "${DIR}/gpgmda_decrypt_msg_once ${email_address}" '{}' "${maildir}"
+	else
+		log "skipping decryption of ${input_folder} because 0 files were found"
+	fi
+
+}
+
+
+
+check_maildirs_by_file_count()
+{
+	files_in_gpgmaildir=$(find "${gpgmaildir}" -type f | wc -l)
+	files_in_maildir=$(find "${maildir}" -type f | wc -l)
+
+	if [[ "${files_in_gpgmaildir}" == "${files_in_maildir}" ]]
+	then
+		log "file counts (${files_in_gpgmaildir}) match, skipping update"
+		return 0
+	else
+		log "file counts differ:"
+		log "files_in_gpgmaildir ${gpgmaildir} =${files_in_gpgmaildir}"
+		log "files_in_maildir ${maildir} =${files_in_maildir}"
+		return 1
+	fi
+}
+
+
+rsync_files_transferred=$(cat /dev/shm/.gpgmda_rsync_last_new_mail_"${email_address}" | grep 'Number of files transferred:' | cut -d ':' -f 2 | tr -d '[:space:]')
+
+
+log "rsync_files_transferred: ${rsync_files_transferred}"
+
+if [[ "${rsync_files_transferred}" == "0" ]]
+then
+	log "rsync transferred 0 files"
+else
+	warm_up_gpg || fail "problem warming up gpg"
+	cat /dev/shm/.gpgmda_rsync_last_new_mail_"${email_address}" | grep -v exists | grep gpgMaildir | grep '^>f' | cut -d ' ' -f 2 | cut -d '/' -f 2- | parallel --halt-on-error 1 --keep-order --eta -j+0 "${DIR}"/gpgmda_decrypt_msg_once "${email_address}" "${gpgmaildir}"/'{}' "${maildir}"
+fi
+
+#see if there are files that were not decrypted
+if check_maildirs_by_file_count
+then
+	log "check_maildirs_by_file_count() exited 0"
+else
+	log "check_maildirs_by_file_count() exited 1, attempting to decrypt all files"
+	warm_up_gpg || fail "problem warming up gpg"
+	test_and_decrypt_all_files_in_folder "${gpgmaildir}"
+fi
+
+
+exit 0
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
 
 test_and_decrypt_all_files()
 {
-# this goes through every file... much slower than the default method.
-# parallel is GNU parallel http://www.gnu.org/software/parallel/
+	# this goes through every file... much slower than the default method.
+	# parallel is GNU parallel http://www.gnu.org/software/parallel/
 
 	echo "gpgmda_to_maildir test_and_decrypt_all_files()"
 	warm_up_gpg
@@ -91,7 +299,7 @@ test_and_decrypt_all_files()
 	echo -e "\nworking on ${gpgmaildir}/new"
 	echo "email_address: ${email_address}"
 	number_of_files_to_process=`find "${gpgmaildir}/new" -type f | wc -l`
-	echo "about to process ${number_of_files_to_process} files"
+	echo "about to process ${number_of_files_to_process} files from new"
 	if [[ "${number_of_files_to_process}" -gt "0" ]]
 	then
 		echo "attempting to run gnu parallel on new"
@@ -104,7 +312,7 @@ test_and_decrypt_all_files()
 	echo -e "\nworking on ${gpgmaildir}/.sent"
 	echo "email_address: ${email_address}"
 	number_of_files_to_process=`find "${gpgmaildir}/.sent" -type f | wc -l`
-	echo "about to process ${number_of_files_to_process} files"
+	echo "about to process ${number_of_files_to_process} files from .sent"
 	if [[ "${number_of_files_to_process}" -gt "0" ]]
 	then
 		echo "attempting to run gnu parallel on .sent"
@@ -112,48 +320,5 @@ test_and_decrypt_all_files()
 	else
 		echo "skipping decryption of folder .sent because 0 files were found"
 	fi
+
 }
-
-check_maildirs_by_file_count()
-{
-	files_in_gpgmaildir=$(find "${gpgmaildir}" -type f | wc -l)
-	files_in_maildir=$(find "${maildir}" -type f | wc -l)
-
-	if [[ "${files_in_gpgmaildir}" == "${files_in_maildir}" ]]
-	then
-		echo "file counts (${files_in_gpgmaildir}) match, skipping update"
-		return 0
-	else
-		echo "file counts differ:"
-		echo "files_in_gpgmaildir ${gpgmaildir} =${files_in_gpgmaildir}"
-		echo "files_in_maildir ${maildir} =${files_in_maildir}"
-		return 1
-	fi
-}
-
-
-rsync_files_transferred=$(cat /dev/shm/.gpgmda_rsync_last_new_mail_"${email_address}" | grep 'Number of files transferred:' | cut -d ':' -f 2 | tr -d '[:space:]')
-
-
-echo "rsync_files_transferred: ${rsync_files_transferred}"
-
-if [[ "${rsync_files_transferred}" == "0" ]]
-then
-	echo "rsync transferred 0 files"
-else
-	warm_up_gpg || fail "problem warming up gpg"
-	cat /dev/shm/.gpgmda_rsync_last_new_mail_"${email_address}" | grep -v exists | grep gpgMaildir | grep '^>f' | cut -d ' ' -f 2 | cut -d '/' -f 2- | parallel --halt-on-error 1 --keep-order --eta -j+0 "${DIR}"/gpgmda_decrypt_msg_once "${email_address}" "${gpgmaildir}"/'{}'
-fi
-
-#see if there are files that were not decrypted
-if check_maildirs_by_file_count
-then
-	echo "check_maildirs_by_file_count() exited 0"
-else
-	echo "check_maildirs_by_file_count() exited 1, attempting to decrypt all files"
-	warm_up_gpg || fail "problem warming up gpg"
-	test_and_decrypt_all_files
-fi
-
-
-exit 0
diff --git a/run_notmuch b/run_notmuch
--- a/run_notmuch
+++ b/run_notmuch
@@ -2,6 +2,96 @@
 
 # requires: http://www.guru-group.fi/~too/nottoomuch/nottoomuch-addresses/
 
+#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
+#-#-#-# <OPTIONS> #-#-#-#-#-#-#
+
+
+debug=1                                 #uncomment this line to enable debugging output
+                                        #NOTES:
+                                        #       Along with other information, this logs the sha1 of the incoming message plaintext to the logfile.
+                                        #       Comment this out for use in production.
+
+
+
+#-#-#-# <END OPTIONS> #-#-#-#-#
+#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
+
+
+debug="${debug-0}"
+
+if [[ "${debug}" != "1" ]] ; then
+        exec > >(cat /dev/null) 2>&1            #keep script quiet unless debug=1
+fi
+
+if [[ "${debug}" != "1" ]] && [[ "${debug}" != "0" ]] ; then
+        fail "debug must be set to 0 or 1, currently debug=${debug}"    #note this will never actually print anything, because debug != 1, but we want to fail here anyway
+fi
+
+show_help()
+{ cat <<EOF
+
+	TODO
+
+EOF
+}
+
+
+version() { cat <<EOF
+0.5 ALPHA [Aug 20 2013]
+EOF
+}
+
+
+debug_dump_vars="${debug_dump_vars-0}"
+
+usually_dev_null="${usually_dev_null-/dev/null}"
+
+error_exit_code="${error_exit_code-75}"
+
+
+my_pid=$$
+
+dbg()
+{
+        if [[ "${debug}" == "1" ]] ; then
+                return 0                #return true if debug=1
+        else
+                return 1                #debugging is disabled, stop here
+        fi
+}
+
+log()                                   # print log message if debug=1
+{
+        if dbg ; then
+                test -t 1 && logger -s "[stderr][$PPID][${my_pid}] $*" || logger "[$PPID][${my_pid}] $*"
+        fi
+        return $?
+}
+
+fail()                                  # log error and exit
+{
+        log "fail() ERROR: $*"
+        log "fail() EXITING ${error_exit_code}"
+        exit "${error_exit_code}"
+}
+
+on_ERR()
+{
+        prev_line=`caller`
+        log "on_ERR called from line: ${prev_line}"
+        fail "trapped ERR - on_ERR() called in $0 with $*. Exiting"
+}
+
+trap on_ERR ERR                         # from the man docs on set -o errexit
+
+
+
+
+
+
+
+
+
 SOURCE="${BASH_SOURCE[0]}"
 while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
 DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"        # http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
@@ -13,7 +103,7 @@ scriptname=`basename "$0"`
 min_argcount=1
 usage="mode=update_notmuch_db/query_address_db/build_address_db/update_address_db/custom/notmuch) user@domain.com [querystring]"
 
-test "$#" -ge "${min_argcount}" || { echo -e "Too few arguments\n$0 ${usage}" && exit 1 ; } #"-ge=>=" "-gt=>" "-le=<=" "-lt=<" "-ne=!="
+test "$#" -ge "${min_argcount}" || { log -e "Too few arguments\n$0 ${usage}" && exit 1 ; } #"-ge=>=" "-gt=>" "-le=<=" "-lt=<" "-ne=!="
 
 mode=`echo "${1}" | cut -d '=' -f 2`
 shift
@@ -22,15 +112,15 @@ email_address="${1}"
 username=$(echo "${email_address}" | cut -d '@' -f 1)
 shift
 
-echo "mode=$mode"
+log "mode=$mode"
 
 email_archive_folder=/home/user/__email_folders
 
 notmuch_config_folder="${email_archive_folder}/_notmuch_config"
 
-test -d "${notmuch_config_folder}" || { echo "${notmuch_config_folder} not found or is not a directory, exiting" && exit 1 ;}
+test -d "${notmuch_config_folder}" || { log "${notmuch_config_folder} not found or is not a directory, exiting" && exit 1 ;}
 
-touch "${notmuch_config_folder}"/.dir_write_test && rm "${notmuch_config_folder}"/.dir_write_test || { echo "${notmuch_config_folder} not writable, exiting" && exit 1 ;}
+touch "${notmuch_config_folder}"/.dir_write_test && rm "${notmuch_config_folder}"/.dir_write_test || { log "${notmuch_config_folder} not writable, exiting" && exit 1 ;}
 
 
 configure_notmuch()
@@ -59,9 +149,9 @@ create_notmuch_config()
 
 
 NOTMUCH_CONFIG="${notmuch_config_folder}/.notmuch-config"
-echo "${NOTMUCH_CONFIG}"
+log "${NOTMUCH_CONFIG}"
 
-test -s "${NOTMUCH_CONFIG}" || { echo "making ${NOTMUCH_CONFIG}" && create_notmuch_config ; }
+test -s "${NOTMUCH_CONFIG}" || { log "making ${NOTMUCH_CONFIG}" && create_notmuch_config ; }
 
 
 if [[ "${mode}" == "update_notmuch_db" ]]
@@ -70,12 +160,12 @@ then
 
 elif [[ "${mode}" == "custom" ]]
 then
-	echo "$NOTMUCH_CONFIG"
+	log "$NOTMUCH_CONFIG"
 	NOTMUCH_CONFIG="${NOTMUCH_CONFIG}" notmuch search --output=files "id:<1331789904.35708.YahooMailNeo@web39304.mail.mud.yahoo.com>" || exit 1
 
 elif [[ "${mode}" == "notmuch" ]]
 then
-	echo "$NOTMUCH_CONFIG"
+	log "$NOTMUCH_CONFIG"
 	NOTMUCH_CONFIG="${NOTMUCH_CONFIG}" notmuch "$@" || exit 1
 
 elif [[ "${mode}" == "query_address_db" ]]
@@ -92,7 +182,7 @@ then
 	XDG_CONFIG_HOME="${notmuch_config_folder}" NOTMUCH_CONFIG="${NOTMUCH_CONFIG}" "${DIR}"/nottoomuch-addresses.sh --update
 
 else
-	echo "invalid mode ${mode}, exiting" && exit 1
+	log "invalid mode ${mode}, exiting" && exit 1
 fi
 
 exit 0
