all kinds of changes

diff --git a/gpgmda_to_maildir b/gpgmda_to_maildir
--- a/gpgmda_to_maildir
+++ b/gpgmda_to_maildir
@@ -56,7 +56,8 @@ dbg()
 log()                                   # print log message if debug=1
 {
         if dbg ; then
-                test -t 1 && logger -s "[stderr][$PPID][${my_pid}] $*" || logger "[$PPID][${my_pid}] $*"
+	time_now=`date +%s`
+                test -t 1 && logger -s "[$time_now][stderr][$PPID][${my_pid}] $*" || logger "[$time_now][$PPID][${my_pid}] $*"
         fi
         return $?
 }
@@ -65,8 +66,10 @@ fail()                                  # log error and exit
 {
         log "fail() ERROR: $*"
         log "fail() EXITING ${error_exit_code}"
-        exit "${error_exit_code}"
+        exit "${error_exit_code-1}"
 }
+
+
 
 on_ERR()
 {
@@ -82,10 +85,17 @@ SOURCE="${BASH_SOURCE[0]}"
 while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
 DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"        # http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
 
+test -x "${DIR}/gpgmda_decrypt_msg" || { echo "${DIR}/gpgmda_decrypt_msg is not executiable, please \"chmod +x ${DIR}/gpgmda_decrypt_msg\" and try again. Exiting." && exit 1 ; }
+
+
+
 #source "${DIR}"/bash_import_set_defaults                # set -o nounset; set -o errtrace; set -o errexit; set -o pipefail
 source ~/cfg/bash_libs/shell_command_lock/shell_command_lock
 
+
 email_archive_folder="/home/user/__email_folders"
+
+test -d "${email_archive_folder}" || { echo "${email_archive_folder} not found. Exiting." ; exit 1 ; }
 
 my_pid=$$
 
@@ -101,21 +111,23 @@ email_address="${1}"
 
 gpgMaildir_archive_folder="${email_archive_folder}/_gpgMaildirs/${email_address}"
 
+test -d "${gpgMaildir_archive_folder}" || { echo "${gpgMaildir_archive_folder} not found, exiting." ; exit 1 ; }
+
 log "gpgmda_to_maildir using gpgMaildir_archive_folder: ${gpgMaildir_archive_folder}"
 
 gpgmaildir="${gpgMaildir_archive_folder}/gpgMaildir"
 
+test -d "${gpgmaildir}" || { echo "${gpgmaildir} not found, exiting." ; exit 1 ; }
+
 Maildir_archive_folder="${email_archive_folder}/_Maildirs/${email_address}"
+
+test -d "${Maildir_archive_folder}" || { echo "${Maildir_archive_folder} not found, exiting." ; exit 1 ; }
 
 maildir="${Maildir_archive_folder}/Maildir"
 
+test -d "${maildir}" || { echo "${maildir} not found, exiting." ; exit 1 ; }
 
-fail()
-{
-        log "fail() ERROR: $*"
-        log "fail() EXITING"
-        exit 1
-}
+
 
 
 log "Checking for default-recipient in ~/.gnupg/gpg.conf"
@@ -143,7 +155,8 @@ warm_up_gpg()
 	while [[ "${decrypt_test}" != "1" ]]; do
 		log "generating gpg test string"
 		test_string=$(random_string) || fail "something went wrong generating a random test string"
-		echo "${test_string}" | gpg --yes --trust-model always --throw-keyids --encrypt -o - | gpg --decrypt | grep "${test_string}" && decrypt_test=1
+		log "warm_up_gpg test_string: ${test_string}"
+		echo "warm_up_gpg() test_string: ${test_string}" | gpg --yes --trust-model always --throw-keyids --encrypt -o - | gpg --decrypt 2>&1 | grep "${test_string}" && decrypt_test=1
 	done
 	log "done warming up gpg"
 }
@@ -159,14 +172,15 @@ test_and_decrypt_all_files_in_folder()
 
 	warm_up_gpg
 
-	log -e "\nworking on ${input_folder}"
-	log "email_address: ${email_address}"
+	log "test_and_decrypt_all_files_in_folder() working on ${input_folder}"
+	log "test_and_decrypt_all_files_in_folder() email_address: ${email_address}"
 	number_of_files_to_process=`find "${input_folder}" -type f | wc -l`
 	log "about to process ${number_of_files_to_process} files from ${input_folder}"
 	if [[ "${number_of_files_to_process}" -gt "0" ]]
 	then
 		log "attempting to run gnu parallel on ${input_folder}"
-		find "${input_folder}" -type f | parallel --gnu --halt-on-error 1 --keep-order --eta -j+0 "${DIR}/gpgmda_decrypt_msg ${email_address}" '{}' "${maildir}"
+#		find "${input_folder}" -type f | parallel --gnu --halt-on-error 1 --keep-order --eta -j+0 "${DIR}/gpgmda_decrypt_msg ${email_address}" '{}' "${maildir}" 2>&1 | ts %s 2>&1 > /dev/stdout 2>&1
+		find "${input_folder}" -type f | parallel --gnu --halt-on-error 0 --keep-order -j+0 "${DIR}/gpgmda_decrypt_msg ${email_address}" '{}' "${maildir}" 2>&1 | ts %s 2>&1 > /dev/stdout 2>&1
 	else
 		log "skipping decryption of ${input_folder} because 0 files were found"
 	fi
@@ -176,6 +190,7 @@ test_and_decrypt_all_files_in_folder()
 
 check_maildirs_by_file_count()
 {
+	log "gpgmda_to_maildir check_maildirs_by_file_count()"
 	files_in_gpgmaildir=$(find "${gpgmaildir}" -type f | wc -l)
 	files_in_maildir=$(find "${maildir}" -type f | wc -l)
 
@@ -192,18 +207,34 @@ check_maildirs_by_file_count()
 }
 
 
-rsync_files_transferred=$(cat /dev/shm/.gpgmda_rsync_last_new_mail_"${email_address}" | grep 'Number of files transferred:' | cut -d ':' -f 2 | tr -d '[:space:]')
+parse_rsync_log()
+{
+	cat /dev/shm/.gpgmda_rsync_last_new_mail_"${email_address}" | grep -v exists | grep gpgMaildir | grep '^>f' | cut -d ' ' -f 2 | cut -d '/' -f 2-
+}
 
 
-log "rsync_files_transferred: ${rsync_files_transferred}"
-
-if [[ "${rsync_files_transferred}" == "0" ]]
+if test -s /dev/shm/.gpgmda_rsync_last_new_mail_"${email_address}"
 then
-	log "rsync transferred 0 files"
+	rsync_files_transferred=$(cat /dev/shm/.gpgmda_rsync_last_new_mail_"${email_address}" | grep 'Number of files transferred:' | cut -d ':' -f 2 | tr -d '[:space:]')
+	log "rsync_files_transferred: ${rsync_files_transferred}"
+
+	if [[ "${rsync_files_transferred}" == "0" ]]
+	then
+		log "rsync transferred 0 files, skipping decrypt"
+	else
+		log "rsync_files_transferred: ${rsync_files_transferred}, about to warm up gpg"
+		warm_up_gpg || fail "problem warming up gpg"
+
+		log "parse_rsync_log output:"
+		parse_rsync_log
+
+#		parse_rsync_log | parallel --gnu --halt-on-error 1 --keep-order --eta -j+0 "${DIR}"/gpgmda_decrypt_msg "${email_address}" "${gpgmaildir}"/'{}' "${maildir}" 2>&1 | ts %s 2>&1 > /dev/stdout 2>&1
+		parse_rsync_log | parallel --gnu --halt-on-error 0 --keep-order -j+0 "${DIR}"/gpgmda_decrypt_msg "${email_address}" "${gpgmaildir}"/'{}' "${maildir}" 2>&1 | ts %s 2>&1 > /dev/stdout 2>&1
+	fi
 else
-	warm_up_gpg || fail "problem warming up gpg"
-	cat /dev/shm/.gpgmda_rsync_last_new_mail_"${email_address}" | grep -v exists | grep gpgMaildir | grep '^>f' | cut -d ' ' -f 2 | cut -d '/' -f 2- | parallel --halt-on-error 1 --keep-order --eta -j+0 "${DIR}"/gpgmda_decrypt_msg "${email_address}" "${gpgmaildir}"/'{}' "${maildir}"
+	echo "/dev/shm/.gpgmda_rsync_last_new_mail_${email_address} not found. Skipping parse stage."
 fi
+
 
 #see if there are files that were not decrypted
 if check_maildirs_by_file_count
