rewrite mail_update in python, make one notmuch database cover all maildirs, numerious bug fixes, gpg support in alot

diff --git a/gpgmda b/gpgmda
--- a/gpgmda
+++ b/gpgmda
@@ -30,8 +30,12 @@
 
 
 debug=1 				#uncomment this line to enable debugging output
+					#NOTES:
+					#	Along with other information, this logs the sha1 of the incoming message plaintext to the logfile.
+					#	Comment this out for use in production.
 
-tarcmd="/usr/local/src/tar-1.26/output/bin/tar"		#tar must support the --transform switch, uncomment this line if you had to compile tar manually
+
+#tarcmd="/usr/local/src/tar-1.26/output/bin/tar"	#tar must support the --transform switch, uncomment this line if you had to compile tar manually
 
 
 #-#-#-# <END OPTIONS> #-#-#-#-#
@@ -67,7 +71,7 @@ show_help()
 	(debugging output here if debug=1)
 
 	ls ~/gpgMaildir/new/meG4dNyfrUapZwmPPXUwHh4O4EIQmDkIosa+oVD2
-	-r--r-----. 1 inuser mailreaders 1.3K Jan  1  1970 /home/default/gpgMaildir/new/meG4dNyfrUapZwmPPXUwHh4O4EIQmDkIosa+oVD2 
+	-r--r-----. 1 inuser mailreaders 1.3K Jan  1  1970 /home/default/gpgMaildir/new/meG4dNyfrUapZwmPPXUwHh4O4EIQmDkIosa+oVD2
 	(this is a gpg encrypted file that contains a tar file)
 
 	see gpgmda.README for a complete example
@@ -91,7 +95,7 @@ set -o pipefail		 	# If set, the return value of a pipeline is the value of the 
 				# to exit with a non-zero status, or zero if all commands in the pipeline exit successfully.
 
 version() { cat <<EOF
-0.4 ALPHA [Feb 25 2012]
+0.5 ALPHA [Aug 20 2013]
 EOF
 }
 
@@ -133,8 +137,10 @@ fail() 					# log error and exit
 	exit "${error_exit_code}"
 }
 
-function on_ERR()
+on_ERR()
 {
+	prev_line=`caller`
+	log "on_ERR called from line: ${prev_line}"
 	fail "trapped ERR - on_ERR() called in $0 with $*. Exiting"
 }
 
@@ -202,7 +208,12 @@ startup_tests()				#executed every run
 
 	id -Z > /dev/null 2>&1 && 		log "kernel is selinux enabled"
 
+
 	check_tar_command || fail "problem with tar, exiting"
+
+	cat /etc/group | grep mailreaders > /dev/null || fail "the mailreaders group does not exist. please create it. exiting."
+
+	groups | grep mailreaders > /dev/null || fail "you must be in the mailreaders group, exiting. Note: if you are executing this script from postfix, the mailreaders group must be the users primary group due to a limitation documented in \"man 8 local\". To fix, run \"usermod -g mailreaders ${USER}\""
 
 	grep "^default-recipient" ~/.gnupg/gpg.conf > /dev/null 2>&1 || fail "default-recipient is not defined in ~/.gnupg/gpg.conf, please set it and try again"
 
@@ -210,9 +221,7 @@ startup_tests()				#executed every run
 
 	test -s ~/.gnupg/pubring.gpg || fail "~/.gnupg/pubring.gpg not found or is zero bytes, please install at least 1 public key and try again"
 
-	cat /etc/group | grep mailreaders > /dev/null || fail "the mailreaders group does not exist. please create it. exiting."
 
-	groups | grep mailreaders > /dev/null || fail "you must be in the mailreaders group, exiting. Note: if you are executing this script from postfix, the mailreaders group must be the users primary group due to a limitation documented in \"man 8 local\""
 
 	if dbg ; then
 
@@ -271,7 +280,7 @@ fi
 
 gpgMaildir="${1-$HOME/gpgMaildir/new/}"
 
-echo "${gpgMaildir}" | grep "^[./]" | grep "[/]$" > /dev/null || fail "If you specify the destination folder it must start with a dot (.) or slash (/) and end with a slash (/). Exiting."
+echo "${gpgMaildir}" | grep "^[./]" | grep "[/]$" > /dev/null || fail "If you specify the destination Maildir folder it must start with a dot (.) or slash (/) and end with a slash (/). Exiting."
 
 test -d "${gpgMaildir}" || mkdir -p "$gpgMaildir" || fail "unable to mkdir $gpgMaildir, exiting"
 
@@ -336,8 +345,10 @@ sha1sum | cut -d ' ' -f 1)
 
 gpg_exit_status="$?"
 
-log "message SHA1=${sha1}"			# computing SHA1 is just an example. Feel free to replace sha1sum with any message plaintext processing script.
-						# note it operates on a copy of STDIN and therefore can not modify the data on it's way to gpg.
+log "message SHA1=${sha1}"		# computing SHA1 is just an example. Feel free to replace sha1sum with any message plaintext processing script.
+					# notes:
+					#	sha1sum is operating on a copy of STDIN
+					#	remember to disable logging.
 
 if [[ "${gpg_exit_status}" != 0 ]]; then
 	fail "the pipe to or from gpg returned a non-zero exit status ${gpg_exit_status}, exiting."
@@ -350,7 +361,7 @@ chmod 440 -- "${output_file}" || log "Problem setting perms 400 on ${output_file
 
 dbg && log $(ls -al -- "${output_file}")
 
-#  last step is to fix ctime
+#  last step is to fix ctime. This only removes some information due to the sequential number of inodes.
 #
 #  ctime is not (easily) settable to the past (without changing the system clock, or working on the disk offline),
 #  therefore we must update _all_ ctimes to prevent a timing information leak for messages.
@@ -365,10 +376,10 @@ lockdir="/dev/shm/${lockdir_name}_ctime_update_lock"
 remove_lock()
 {
 	test -d "${lockdir}" || fail "${lockdir} is not a directory, this should not happen, exiting"
-	[[ "$(ls -A "${lockdir}")" ]] && fail "${lockdir} not empty, this should not happen, exiting" || rm -r -- "${lockdir}"
+	[[ "$(ls -A "${lockdir}")" ]] && fail "${lockdir} not empty, this should not happen, exiting" || { rm -r -- "${lockdir}" && log "Lock removed" ; }
 }
 
-log "obtaining lock in preparation update all ctimes"
+log "obtaining lock in preparation to update all ctimes"
 if ! mkdir "${lockdir}" 2> /dev/null; then				# obtain atomic lock
 	log "$0 $* is already running the ctime update, skipping."
 else
@@ -377,9 +388,9 @@ else
 	touch -t 197001010000.00 -- "${gpgMaildir}/"* > "${usually_dev_null}" 2>&1		# note that the wildcard must be outside the quote for this to work
 	remove_lock										# note we have not modified the trap we set on ERR, so if this script is canceled while in the critical section but before
 												# remove_lock is called, then it could leave a stale lock. The lock is stored in /dev/shm so it's cleared on reboot.
+	log "done updating ctimes"
 fi												# very unlikely failure mode... but could be fixed
 
-log "done updating ctimes"
 
 dbg && test -t 1 && stat -- "${output_file}" 			# stat does not modify atime, mtime or ctime
 dbg && test -t 1 && lsattr -- "${output_file}"			# lsattr does not modify atime, mtime or ctime
diff --git a/gpgmda_decrypt_msg_once b/gpgmda_decrypt_msg_once
--- a/gpgmda_decrypt_msg_once
+++ b/gpgmda_decrypt_msg_once
@@ -7,34 +7,43 @@ while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
 DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"        # http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
 
 source "${DIR}"/bash_import_set_defaults                # set -o nounset; set -o errtrace; set -o errexit; set -o pipefail
-source "${DIR}"/bash_import_email_archive_folder        # defines email_archive_folder
+
+email_archive_folder="/home/user/__email_folders"
 
 my_pid=$$
 
 argcount=2
 usage="email@domain.com gpg_encrypted_file"
 
-test "$#" -eq "${argcount}" || { echo "$0 ${usage}" && exit 1 ; } #"-ge=>=" "-gt=>" "-le=<=" "-lt=<" "-ne=!="
+test "$#" -eq "${argcount}" || { echo "ERROR:" && echo "$0 ${usage}" && echo "gpgmda_decrypt_msg_once was passed ${#} args:" && echo "$@" && exit 1 ; } #"-ge=>=" "-gt=>" "-le=<=" "-lt=<" "-ne=!="
+
+echo -e "\ngpgmda_decrypt_msg_once was passed ${#} args:" && echo "$@"
 
 email_address="${1}"
 
-gpgMaildir_archive_folder="${email_archive_folder}/_gpgMaildir_${email_address}_archive"
+
+gpgMaildir_archive_folder="${email_archive_folder}/_gpgMaildirs/${email_address}_archive"
+
+echo "gpgmda_to_maildir using gpgMaildir_archive_folder: ${gpgMaildir_archive_folder}"
 
 gpgmaildir="${gpgMaildir_archive_folder}/_gpgMaildirs/gpgMaildir"
 
-maildir="${gpgMaildir_archive_folder}/_Maildirs/Maildir"
+Maildir_archive_folder="${email_archive_folder}/_Maildirs/${email_address}_archive"
+
+maildir="${Maildir_archive_folder}/_Maildirs/Maildir"
+
 
 gpgfile="${2}"
-#echo "gpgfile=${gpgfile}"
+echo "gpgfile=${gpgfile}"
 
 gpgfile_name=$(basename "$gpgfile")
-#echo "gpgfile_name=${gpgfile_name}"
+echo "gpgfile_name=${gpgfile_name}"
 
 gpgfile_folder=$(dirname "${gpgfile}")
-#echo "gpgfile_folder=${gpgfile_folder}"
+echo "gpgfile_folder=${gpgfile_folder}"
 
 gpgfile_subfolder=$(basename "${gpgfile_folder}")
-#echo "gpgfile_subfolder=${gpgfile_subfolder}"
+echo "gpgfile_subfolder=${gpgfile_subfolder}"
 
 #keyid="${3}"
 
@@ -42,13 +51,13 @@ if test ! -s "${gpgfile}"
 then
 	echo "FOUND ZERO LENGTH FILE, CHECK THE MAILSERVER LOGS - ${gpgfile}"
 	timestamp=$(date +%s.%N)
-	mv "${gpgfile}" /tmp/"${gpgfile_name}"."${timestamp}"
+#	mv "${gpgfile}" /tmp/"${gpgfile_name}"."${timestamp}"
 	exit 0
 fi
 
 file_previously_decrypted=0
 
-#there are better ways to do this...like using find for starters
+#there are better ways to do this...like using find
 
 test -s "${maildir}/new/"*".${gpgfile_name}" && file_previously_decrypted=1
 
@@ -59,11 +68,11 @@ test -s "${maildir}/.sent/"*".${gpgfile_name}" && file_previously_decrypted=1
 
 if [ "${file_previously_decrypted}" == "1" ]; then
 
-	:
-	#echo "skipping existing file"
+	#:
+	echo "skipping existing file"
 else
-	ls -al "${gpgfile}"
-	echo  "maildir=${maildir} gpgfile_subfolder=${gpgfile_subfolder}"
+	ls -al "${gpgfile}" || { echo "Unable to run ls on ${gpgfile}, exiting without decryption." && exit 1 ; }
+#	echo  "maildir=${maildir} gpgfile_subfolder=${gpgfile_subfolder}"
 	gpg2 -o - --decrypt "${gpgfile}" | tar --transform="s/$/.${gpgfile_name}/" -C  "${maildir}/${gpgfile_subfolder}" -xvf -
 
 fi
diff --git a/mail_update b/mail_update
--- a/mail_update
+++ b/mail_update
@@ -1,50 +1,313 @@
-#!/bin/bash
+#!/usr/bin/env python
+# -*- coding: utf8 -*- 
 
-SOURCE="${BASH_SOURCE[0]}"
-while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
-DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"        # http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
-
-source "${DIR}"/bash_import_set_defaults                # set -o nounset; set -o errtrace; set -o errexit; set -o pipefail
-source "${DIR}"/bash_import_lock_unique_cmd_line        #implements locking so that two identical commands can not be run at the same time.
-source "${DIR}"/bash_import_email_archive_folder        # defines email_archive_folder
-
-scriptname=`basename "$0"`
-argcount=1
-usage="email@domain.com"
-
-test "$#" -eq "${argcount}" || { echo "$0 ${usage}" && exit 1 ; } #"-ge=>=" "-gt=>" "-le=<=" "-lt=<" "-ne=!="
-
-email_address="${1}"
-
-grep "${email_address}" "${DIR}"/.noupdate && { echo "${email_address} must be removed from ${DIR}/.noupdate before mail_update will attempt to update the mailbox, exiting 0." && exit 0 ; }
-
-source "${DIR}"/bash_import_get_archive_folder #must be done after email_address is set
-#defines get_archive_folder()
-
-archive_folder=$(get_archive_folder) || { echo "error getting archive_folder, you may need to execute ./setup_new_account_folders if this is a new account" && exit 1 ; }
-
-folder_type=$(basename "${archive_folder}" | cut -d '_' -f 2)
-
-echo "folder_type=${folder_type}"
-
-if [[ "${folder_type}" == "getmail" ]];
-then
-	"${DIR}"/getmail_gmail "${email_address}" || exit 1
+from __future__ import print_function
+from __future__ import unicode_literals
 
 
-elif [[ "${folder_type}" == "gpgMaildir" ]];
-then
-	"${DIR}"/gpgmda_rsync "${email_address}" || ( echo "gpgmda_rsync exited nonzero" && exit 1 )
+# todo: locking to prevent multiple instances of mail_update
 
-	"${DIR}"/gpgmda_to_maildir "${email_address}" || ( echo "gpgmda_to_maildir exited nonzero" && exit 1 )
-else
-        echo "unknown folder type \"${folder_type}\", exiting" && exit 1
-fi
-
-
-"${DIR}"/run_notmuch --update_address_db "${email_address}" || exit 1
-
-"${DIR}"/run_notmuch --update_notmuch_db "${email_address}" || exit 1
+import sys
+import os
+import traceback
+import optparse
+import time
+import subprocess
+from os.path import exists
 
 
-exit 0
+
+def run_notmuch(email_address, mode, query=""):
+	print("run_notmuch():",mode)
+	notmuch_config_folder=email_archive_folder+"/_notmuch_config"
+	notmuch_config_file=notmuch_config_folder+"/.notmuch_config"
+	make_notmuch_config(email_address)
+
+
+	if mode == "update_notmuch_db":
+		command="NOTMUCH_CONFIG="+notmuch_config_file+" notmuch new"
+		return_code = os.system(command)
+		if return_code != 0:
+			print("\"notmuch new\" returned nonzero, exiting")
+			os._exit(1)
+
+
+	elif mode == "query_notmuch":
+		command="NOTMUCH_CONFIG="+notmuch_config_file+" notmuch " + query
+		return_code = os.system(command)
+		if return_code != 0:
+			print("\"notmuch "+query+ "\" returned nonzero, exiting")
+			os._exit(1)
+
+
+	elif mode == "query_address_db":
+		command="XDG_CONFIG_HOME="+notmuch_config_folder+" NOTMUCH_CONFIG="+notmuch_config_file+" "+gpgmda_program_folder+"/nottoomuch-addresses.sh "+query
+		return_code = os.system(command)
+		if return_code != 0:
+			print("\"nottoomuch-addresses.sh\" returned nonzero, exiting")
+			os._exit(1)
+
+
+	elif mode == "build_address_db":
+		command="XDG_CONFIG_HOME="+notmuch_config_folder+" NOTMUCH_CONFIG="+notmuch_config_file+" "+gpgmda_program_folder+"/nottoomuch-addresses.sh --update --rebuild"
+		return_code = os.system(command)
+		if return_code != 0:
+			print("\"nottoomuch-addresses.sh\" returned nonzero, exiting")
+			os._exit(1)
+
+
+	elif mode == "update_address_db":
+		command="XDG_CONFIG_HOME="+notmuch_config_folder+" NOTMUCH_CONFIG="+notmuch_config_file+" "+gpgmda_program_folder+"/nottoomuch-addresses.sh --update"
+		return_code = os.system(command)
+		if return_code != 0:
+			print("\"nottoomuch-addresses.sh\" returned nonzero, exiting")
+			os._exit(1)
+
+	else:
+		print("invalid mode",mode,"exiting.")
+		os._exit(1)
+
+
+
+
+
+def make_notmuch_config(email_address):
+	username=email_address.split("@")[0]
+
+	notmuch_config="""
+[database]
+path="""+email_archive_folder+"""/_Maildirs
+
+[user]
+name="""+username+"""
+primary_email="""+email_address+"""
+
+[new]
+tags=unread;inbox;
+
+[maildir]
+synchronize_flags=false
+"""
+
+	notmuch_config_file_location=email_archive_folder+"/_notmuch_config/.notmuch_config"
+	print("writing notmuch config to:", notmuch_config_file_location)
+	notmuch_config_file_handle=open(notmuch_config_file_location, "w")
+	notmuch_config_file_handle.write(notmuch_config)
+	notmuch_config_file_handle.close()
+
+
+
+def start_alot(email_address):
+	alot_config=subprocess.Popen([gpgmda_program_folder+"/make_alot_config", email_address], stdout=subprocess.PIPE).communicate()
+	alot_theme=subprocess.Popen([gpgmda_program_folder+"/make_alot_theme"], stdout=subprocess.PIPE).communicate()
+
+	alot_config_f = open('/dev/shm/__alot_config_'+email_address,'wb')
+	alot_theme_f = open('/dev/shm/__alot_theme_'+email_address,'wb')
+
+	alot_config_f.write(alot_config[0])
+	alot_theme_f.write(alot_theme[0])
+
+	alot_config_f.close()
+	alot_theme_f.close()
+
+	notmuch_config_folder = email_archive_folder+'/_notmuch_config'
+
+	print("starting alot",)
+	
+	alot_ver=os.system(' '.join(['alot', '--version']))
+	
+	alot_p=os.system(' '.join(['alot', '-C', '256', '--debug-level=debug', '--logfile=/dev/shm/__alot_log', '--notmuch-config', notmuch_config_folder+'/.notmuch_config', '--mailindex-path', email_archive_folder+'/_Maildirs', '-c', '/dev/shm/__alot_config_'+email_address]))
+	
+
+
+def load_ssh_key(email_address):
+	if 'gmail' in email_address:
+		return
+
+	ssh_key='/home/user/.ssh/id_rsa__'+email_address
+
+	loaded_ssh_keys_p=subprocess.Popen(['ssh-add','-l'], stdout=subprocess.PIPE)
+	loaded_ssh_keys_p_output = loaded_ssh_keys_p.communicate()[0]
+	loaded_ssh_key_list = loaded_ssh_keys_p_output.split(b'\n')
+
+	print("ssh-add -l output:")
+	for line in loaded_ssh_key_list:
+		print(line)
+
+	found_key = 0
+	for key in loaded_ssh_key_list:
+		if str(ssh_key) in str(key):
+			found_key=1
+		
+	if found_key != 1:
+		ssh_add_p = subprocess.Popen(['ssh-add', ssh_key])
+		ssh_add_p_output = ssh_add_p.communicate()
+		if ssh_add_p.returncode != 0:
+			print("something went wrong adding the ssh_key, exiting")
+			os._exit(1)
+
+
+
+def rsync_mail(email_address):
+	load_ssh_key(email_address)
+
+	rsync_p = subprocess.Popen(['rsync', '--ignore-existing', '--size-only', '-t', '--whole-file', '-L', '-c', '--stats', '-i', '-r', '-vv', email_address+':gpgMaildir', email_archive_folder+'/_gpgMaildirs/'+email_address+'_archive/_gpgMaildirs/'], stdout=subprocess.PIPE)
+	rsync_p_output=rsync_p.communicate()
+	for line in rsync_p_output[0].split(b'\n'):
+		print(line)
+
+
+	print("rsync_p.returncode:",rsync_p.returncode)
+	if rsync_p.returncode != 0:
+		print("rsync did not return 0, exiting")
+		os._exit(1)
+
+
+	rsync_logfile_handle = open("/dev/shm/.gpgmda_rsync_last_new_mail_"+email_address,'wb')
+	rsync_logfile_handle.write(rsync_p_output[0])
+	rsync_logfile_handle.close()
+
+
+def decrypt_mail(email_address):
+	print("mail_update decrypt_mail()")
+	gpgmda_to_maildir_p = subprocess.Popen([gpgmda_program_folder+"/gpgmda_to_maildir", email_address], stdout=subprocess.PIPE)
+	print("created gpgmda_to_maildir_p, about to read output via .communicate()")
+	gpgmda_to_maildir_p_output = gpgmda_to_maildir_p.communicate()[0]
+	print("gpgmda_to_maildir output")
+	gpgmda_to_maildir_p_output_decoded = gpgmda_to_maildir_p_output.decode('utf-8')
+
+	for line in gpgmda_to_maildir_p_output_decoded.split('\n'):
+		print(line)
+
+	print("gpgmda_to_maildir_p.returncode:", gpgmda_to_maildir_p.returncode)
+
+	if gpgmda_to_maildir_p.returncode != 0:
+		print("gpgmda_to_maildir did not return 0, exiting")
+		os._exit(1)
+
+	print("(exiting 0) mail_update decrypt_mail()")
+
+
+
+
+def update_notmuch_db(email_address):
+	run_notmuch(email_address, "update_notmuch_db")
+
+
+def update_notmuch_address_db(email_address):
+	run_notmuch(email_address, "update_address_db")
+
+
+def update_notmuch_address_db_build(email_address):
+	run_notmuch(email_address, "build_address_db")
+
+
+def query_notmuch(email_address, query):
+	run_notmuch(email_address, "query_notmuch", query)
+
+
+
+
+def main():
+
+	global options, args
+	print(options)
+
+	email_address=args[0]
+
+	global gpgmda_program_folder
+	gpgmda_program_folder = os.path.dirname(os.path.realpath(__file__))
+
+	global email_archive_folder
+	email_archive_folder = "/home/user/__email_folders"
+
+	gpgMaildir_archive_folder=email_archive_folder+"/_gpgMaildirs/"+email_address+"_archive"
+
+	gpgmaildir=gpgMaildir_archive_folder+"/_gpgMaildirs/gpgMaildir"
+
+	Maildir_archive_folder=email_archive_folder+"/_Maildirs/"+email_address+"_archive"
+
+	maildir=Maildir_archive_folder+"/_Maildirs/Maildir"
+
+	email_archive_type = "gpgMaildir"	#fixme: support getmail
+
+	if options.update:
+
+		noupdate_list=open(gpgmda_program_folder+"/.noupdate",'r').readlines()
+		for item in noupdate_list:
+			if args[0] in item:
+				print(args[0]+" is listed in .noupdate, exiting")
+				os._exit(1)
+		
+
+		if email_archive_type == "gpgMaildir":
+			if not os.path.isdir(gpgMaildir_archive_folder+'/_gpgMaildirs'):
+				print(gpgMaildir_archive_folder+'/_gpgMaildirs', "does not exist, exiting")
+				os._exit(1)
+
+			rsync_mail(email_address)
+			decrypt_mail(email_address)
+
+
+		elif  email_archive_type == "getmail":
+			print('gpgmda_program_folder/getmail_gmail "${email_address}" || exit 1')
+			print("todo, call /getmail_gmail ${email_address}")
+
+		else:
+		        print("unknown folder type", email_archive_type, ", exiting")
+
+	
+		update_notmuch_db(email_address)
+		update_notmuch_address_db(email_address)
+
+
+	if options.read:
+		load_ssh_key(email_address)	#so mail can be sent without having to unlock the key
+		make_notmuch_config(email_address)
+		start_alot(email_address)
+
+
+	if options.multi:
+		query_notmuch(email_address, options.multi)
+		
+
+	if options.address_db_build:
+		update_notmuch_address_db_build(email_address)		
+
+
+if __name__ == '__main__':
+	try:
+        	start_time = time.time()
+        	parser = optparse.OptionParser(formatter=optparse.TitledHelpFormatter(), usage=globals()['__doc__'], version='0.1')
+        	parser.add_option('-v', '--verbose', action='store_true', default=False, help='verbose output')
+        	parser.add_option('-r', '--read', action='store_true', default=False, help='read mail without checking for new mail')
+        	parser.add_option('-u', '--update', action='store_true', default=False, help='update (rsync and decrypt) new mail')
+        	parser.add_option('-a', '--address_query', action='store_true', default=False, help='search for address string')
+        	parser.add_option('-b', '--address_db_build', action='store_true', default=False, help='build address database for use with --address_query')
+        	parser.add_option('-q', '--notmuch_query', dest='multi', action='store', help='notmuch arguments')
+        	(options, args) = parser.parse_args()
+        	if len(args) < 1:
+        		parser.error('missing argument')
+        	if options.verbose: print(time.asctime())
+
+        	exit_code = main()
+
+        	if exit_code is None:
+            		exit_code = 0
+        	if options.verbose: print(time.asctime())
+        	if options.verbose: print('TOTAL TIME IN MINUTES:',)
+        	if options.verbose: print((time.time() - start_time) / 60.0)
+        	sys.exit(exit_code)
+	except KeyboardInterrupt as e:
+        	raise e
+	except SystemExit as e:
+        	raise e
+	except Exception as e:
+		print('ERROR, UNEXPECTED EXCEPTION')
+		print(str(e))
+		traceback.print_exc()
+		os._exit(1)
+
+
+
+
diff --git a/run_notmuch b/run_notmuch
--- a/run_notmuch
+++ b/run_notmuch
@@ -1,43 +1,43 @@
 #!/bin/bash
 
+# requires: http://www.guru-group.fi/~too/nottoomuch/nottoomuch-addresses/
+
 SOURCE="${BASH_SOURCE[0]}"
 while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
 DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"        # http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
 
 source "${DIR}"/bash_import_set_defaults                # set -o nounset; set -o errtrace; set -o errexit; set -o pipefail
-source "${DIR}"/bash_import_lock_unique_cmd_line        # implements locking so that two identical command lines can not run at the same time.
-source "${DIR}"/bash_import_email_archive_folder        # defines email_archive_folder
+source ~/cfg/bash_libs/shell_command_lock/shell_command_lock # implements locking so that two identical command lines can not run at the same time.
 
 scriptname=`basename "$0"`
-min_argcount=2
-max_argcount=3
-usage="(--update_notmuch_db/--query_address_db/--build_address_db/--update_address_db) user@domain.com [querystring]"
+min_argcount=1
+usage="mode=update_notmuch_db/query_address_db/build_address_db/update_address_db/custom/notmuch) user@domain.com [querystring]"
 
-test "$#" -ge "${min_argcount}" || { echo "$0 ${usage}" && exit 1 ; } #"-ge=>=" "-gt=>" "-le=<=" "-lt=<" "-ne=!="
-test "$#" -le "${max_argcount}" || { echo "$0 ${usage}" && exit 1 ; } #"-ge=>=" "-gt=>" "-le=<=" "-lt=<" "-ne=!="
+test "$#" -ge "${min_argcount}" || { echo -e "Too few arguments\n$0 ${usage}" && exit 1 ; } #"-ge=>=" "-gt=>" "-le=<=" "-lt=<" "-ne=!="
 
-mode="${1}"
+mode=`echo "${1}" | cut -d '=' -f 2`
+shift
 
-email_address="${2}"
+email_address="${1}"
 username=$(echo "${email_address}" | cut -d '@' -f 1)
+shift
 
-source "${DIR}"/bash_import_get_archive_folder #must be done after email_address is set
-#defines get_archive_folder()
+echo "mode=$mode"
 
-archive_folder=$(get_archive_folder)
+email_archive_folder=/home/user/__email_folders
 
-notmuch_folder="${archive_folder}/_notmuch"
+notmuch_config_folder="${email_archive_folder}/_notmuch_config"
 
-test -d "${notmuch_folder}" || { echo "${notmuch_folder} not found or is not a directory, exiting" && exit 1 ;}
+test -d "${notmuch_config_folder}" || { echo "${notmuch_config_folder} not found or is not a directory, exiting" && exit 1 ;}
 
-touch "${notmuch_folder}"/.dir_write_test && rm "${notmuch_folder}"/.dir_write_test || { echo "${notmuch_folder} not writable, exiting" && exit 1 ;}
+touch "${notmuch_config_folder}"/.dir_write_test && rm "${notmuch_config_folder}"/.dir_write_test || { echo "${notmuch_config_folder} not writable, exiting" && exit 1 ;}
 
 
 configure_notmuch()
 {
 cat <<EOF
 [database]
-path=${archive_folder}/_Maildirs
+path=${email_archive_folder}/_Maildirs
 
 [user]
 name=${username}
@@ -58,25 +58,39 @@ create_notmuch_config()
 }
 
 
-NOTMUCH_CONFIG="${notmuch_folder}/.notmuch-config_${email_address}"
+NOTMUCH_CONFIG="${notmuch_config_folder}/.notmuch-config"
 echo "${NOTMUCH_CONFIG}"
 
 test -s "${NOTMUCH_CONFIG}" || { echo "making ${NOTMUCH_CONFIG}" && create_notmuch_config ; }
 
 
-if [[ "${mode}" == "--update_notmuch_db" ]]
+if [[ "${mode}" == "update_notmuch_db" ]]
 then
 	NOTMUCH_CONFIG="${NOTMUCH_CONFIG}" notmuch new || exit 1
-elif [[ "${mode}" == "--query_address_db" ]]
+
+elif [[ "${mode}" == "custom" ]]
 then
-	echo "${3}" > /home/default/query
-	XDG_CONFIG_HOME="${notmuch_folder}" NOTMUCH_CONFIG="${NOTMUCH_CONFIG}" ~/_notmuchmail/nottoomuch-addresses.sh "${3}"
-elif [[ "${mode}" == "--build_address_db" ]]
+	echo "$NOTMUCH_CONFIG"
+	NOTMUCH_CONFIG="${NOTMUCH_CONFIG}" notmuch search --output=files "id:<1331789904.35708.YahooMailNeo@web39304.mail.mud.yahoo.com>" || exit 1
+
+elif [[ "${mode}" == "notmuch" ]]
 then
-	XDG_CONFIG_HOME="${notmuch_folder}" NOTMUCH_CONFIG="${NOTMUCH_CONFIG}" ~/_notmuchmail/nottoomuch-addresses.sh --update
-elif [[ "${mode}" == "--update_address_db" ]]
+	echo "$NOTMUCH_CONFIG"
+	NOTMUCH_CONFIG="${NOTMUCH_CONFIG}" notmuch "$@" || exit 1
+
+elif [[ "${mode}" == "query_address_db" ]]
 then
-	XDG_CONFIG_HOME="${notmuch_folder}" NOTMUCH_CONFIG="${NOTMUCH_CONFIG}" ~/_notmuchmail/nottoomuch-addresses.sh --update --rebuild
+#	echo "$@" >> /home/user/query
+	XDG_CONFIG_HOME="${notmuch_config_folder}" NOTMUCH_CONFIG="${NOTMUCH_CONFIG}" "${DIR}"/nottoomuch-addresses.sh "${1}"
+
+elif [[ "${mode}" == "build_address_db" ]]
+then
+	XDG_CONFIG_HOME="${notmuch_config_folder}" NOTMUCH_CONFIG="${NOTMUCH_CONFIG}" "${DIR}"/nottoomuch-addresses.sh --update --rebuild
+
+elif [[ "${mode}" == "update_address_db" ]]
+then
+	XDG_CONFIG_HOME="${notmuch_config_folder}" NOTMUCH_CONFIG="${NOTMUCH_CONFIG}" "${DIR}"/nottoomuch-addresses.sh --update
+
 else
 	echo "invalid mode ${mode}, exiting" && exit 1
 fi
